title: 豪哥博客
author: 豪哥
email: wzhy1234@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hhwyz.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: aihy

# Build settings
# theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
